import { Input } from "@/components/ui/input";

import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardFooter,
  Card,
} from "@/components/ui/card";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

const opportunities = [
  {
    title: "HKOI",
    description:
      "Annual Hong Kong wide competitive programming competition to determine the best of the best.",
    tags: ["Comp. Programming"],
  },
  {
    title: "ESF CoCo 2024",
    description:
      "A secondary school hackathon ran annually by English School Foundations students with tons of workshops and competitions.",
    tags: ["Hackathon", "Workshop"],
  },
  {
    title: "HKCERT CTF",
    description:
      "Hong Kong wide annual Cybersecurity Capture the Flag Competition.",
    tags: ["CTF"],
  },
  {
    title: "Software Engineer",
    description:
      "summer I am too lazy to write more opportunites so these are autogenerated lol",
    tags: [],
  },
  {
    title: "Product Designer (UX/UI)",
    description:
      "Passionate designer to create beautiful and intuitive user experiences.",
    tags: [],
  },
  {
    title: "Marketing Manager",
    description: "Innovative leader to drive our marketing strategy.",
    tags: [],
  },
];

const tags = {
  "Comp. Programming": "Competitive programming and coding challenges",
  Hackathon: "Hackathons and coding events",
  Workshop: "Educational workshops and training",
  CTF: "Capture the flag cybersecurity competitions",
};

export function Search() {
  return (
    <div className="px-4 py-6 space-y-6">
      <div className="sticky top-0 z-10 py-2 outline rounded px-2 outline-0 outline-slate-800 bg-gradient-to-b from-black to-transparent backdrop-blur-[2px]">
        <div className="flex items-center gap-4">
          <div className="flex flex-col gap-1 flex-1">
            <Input
              className="w-full"
              id="search"
              placeholder="Search opportunities"
            />
          </div>
          <div className="flex items-center gap-2 flex-shrink-0 overflow-x-auto">
            <TooltipProvider>
              {Object.keys(tags).map((key, index) => (
                <Tooltip>
                  <TooltipTrigger>
                    <Button
                      key={index}
                      size="sm"
                      variant="outline"
                      title={tags[key]}
                    >
                      {key}
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>{tags[key]}</p>
                  </TooltipContent>
                </Tooltip>
              ))}
            </TooltipProvider>
          </div>
        </div>
      </div>
      <Separator className="w-full" />
      <div className="grid gap-4">
        {opportunities.map((opportunity, index) => (
          <Card key={index}>
            <CardHeader className="text-center">
              <CardTitle className="text-2xl">{opportunity.title}</CardTitle>
              <CardDescription>{opportunity.description}</CardDescription>
            </CardHeader>
            <CardFooter className="flex justify-center">
              <Button>Learn More</Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
}
